name: on release

on:
  workflow_dispatch:
    release:
      types: [created]

jobs:
  publish-npm-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 19
          registry-url: https://npm.pkg.github.com/ohitshan
      - run: npm install
      - run: npm run rollup
      - run: npm run test
      - run: npm run publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
